services:
  - type: web
    name: prepzo
    runtime: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
